import 'package:enerren/model/ClaimModel.dart';
import 'package:enerren/model/PointModel.dart';
import 'package:enerren/model/tmsVehicleModel.dart';

class DetailInsentifModel {
  DateTime dateTime;
  TmsVehicleModel vehicle;
  List<PointModel> pointModels;
  List<ClaimModel> claimModels;
  double currentPoint;
  int latestClaimStatus;
  double multiplePoint;
  double minimClaimPoin;

  DetailInsentifModel({
    this.multiplePoint,
    this.minimClaimPoin,
    this.currentPoint,
    this.vehicle,
    this.pointModels,
    this.dateTime,
    this.claimModels,
    this.latestClaimStatus,
  });

  static List<DetailInsentifModel> listDetailInsentifModelDummy = [
    DetailInsentifModel(
      multiplePoint: 500,
      minimClaimPoin: 100, 
      currentPoint: 250,
      latestClaimStatus: 2,
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleTypeName: "pickup box",
        vehicleNumber: "a 165 esq",
      ),
      claimModels: [
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 2,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
    DetailInsentifModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      dateTime: DateTime.now(),
      currentPoint: 250,
      latestClaimStatus: 1,
      vehicle: TmsVehicleModel(
        driverName: "mardigu 1",
        vehicleTypeName: "pickup box",
        vehicleNumber: "b 165 esq",
      ),
      claimModels: [
        ClaimModel(
          status: 2,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
    DetailInsentifModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      dateTime: DateTime.now(),
      currentPoint: 250,
      latestClaimStatus: 2,
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleTypeName: "pickup box",
        vehicleNumber: "a 165 esq",
      ),
      claimModels: [
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 2,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
    DetailInsentifModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      dateTime: DateTime.now(),
      currentPoint: 250,
      latestClaimStatus: 1,
      vehicle: TmsVehicleModel(
        driverName: "mardigu 1",
        vehicleTypeName: "pickup box",
        vehicleNumber: "b 165 esq",
      ),
      claimModels: [
        ClaimModel(
          status: 2,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
  ];
}
