import 'package:enerren/model/ClaimModel.dart';
import 'package:enerren/model/PointModel.dart';
import 'package:enerren/model/ProductModel.dart';
import 'package:enerren/model/StockModel.dart';
import 'package:enerren/model/tmsVehicleModel.dart';

// 
class HistoryStockModel {
  TmsVehicleModel vehicle;
  DateTime dateTime;
  List<StockModel> stocks;
  int pokect; // pocket 1 balance 2 seep 3 insentif
  List<PointModel> pointModels;
  List<ClaimModel> claimModels;
  int latestClaimStatus;
  double multiplePoint;
  double minimClaimPoin;

  HistoryStockModel({
    this.vehicle,
    this.dateTime,
    this.stocks,
    this.pokect,
    this.pointModels,
    this.claimModels,
    this.latestClaimStatus,
    this.minimClaimPoin,
    this.multiplePoint,
  });

  double get getRemainceBalance =>
      stocks == null ? 0 : stocks.fold(0, (p, e) => p + e.remainingBalance);

  double get getTotalProcessClaim => claimModels == null
      ? 0
      : claimModels
          .where((e) => e.status == 1)
          .fold(0, (p, e) => p + e.point);

  static List<HistoryStockModel> listHistoryStock = [
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 1,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00002",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00003",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00004",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00005",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00006",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "jodi",
        vehicleNumber: "b 1235 ac",
        vehicleTypeName: "pick up",
      ),
      dateTime: DateTime.now(),
      pokect: 2,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 2,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 50,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 1,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "jodi",
        vehicleNumber: "b 1235 ac",
        vehicleTypeName: "pick up",
      ),
      dateTime: DateTime.now(),
      pokect: 2,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 2,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 50,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 1,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "jodi",
        vehicleNumber: "b 1235 ac",
        vehicleTypeName: "pick up",
      ),
      dateTime: DateTime.now(),
      pokect: 2,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 2,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 50,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 1,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 1,
          incomeBalance: 2000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 2,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          flowBalance: 2,
          outcomeBalance: 1000,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 100,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      vehicle: TmsVehicleModel(
        driverName: "jodi",
        vehicleNumber: "b 1235 ac",
        vehicleTypeName: "pick up",
      ),
      dateTime: DateTime.now(),
      pokect: 2,
      stocks: [
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 1,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 900,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
        StockModel(
          typeProcessIo: 1,
          dateTime: DateTime.now(),
          balance: 1000,
          prNumber: "PR00001",
          seepStatus: 2,
          image:
              "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          images: [
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
            "https://www.zahir.info/images/Image_Knowledgebase/Faktur_Setengah_Halaman_Z6/Gbr1.png",
          ],
          products: [
            ProductModel(
              productId: 1,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 50,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
            ProductModel(
              productId: 2,
              productName: "ban",
              sallerName: "Toko Indah Motor",
              totalProduct: 1,
              buyingPrice: 500,
              status: 1,
              image: "https://img.lovepik.com/element/40028/4927.png_300.png",
            ),
          ],
        ),
      ],
    ),
    HistoryStockModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      latestClaimStatus: 2,
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 3,
      claimModels: [
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 500,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
    HistoryStockModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      latestClaimStatus: 2,
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 3,
      claimModels: [
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 400,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
    HistoryStockModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      latestClaimStatus: 1,
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 3,
      claimModels: [
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
    HistoryStockModel(
      multiplePoint: 500,
      minimClaimPoin: 100,
      latestClaimStatus: 1,
      vehicle: TmsVehicleModel(
        driverName: "mardigu",
        vehicleNumber: "b 1234 ac",
        vehicleTypeName: "box",
      ),
      dateTime: DateTime.now(),
      pokect: 3,
      claimModels: [
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 700,
          amount: 125000,
        ),
        ClaimModel(
          status: 1,
          dateTime: DateTime.now(),
          image: "",
          point: 250,
          amount: 125000,
        ),
      ],
      pointModels: [
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
        PointModel(
          numberOder: "9A2102871991",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "beras",
          totalPoint: 1,
        ),
        PointModel(
          numberOder: "9A210287190",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "minyak",
          totalPoint: 2,
        ),
        PointModel(
          numberOder: "9A210287191",
          dateTime: DateTime.now(),
          customer: "pt jaya abadi",
          desc: "garam",
          totalPoint: 3,
        ),
      ],
    ),
  ];
}
